[general]
live_config_reload = true
import = [
  "~/.config/alacritty/gruvbox-dark.toml",
  "~/.config/alacritty/host.toml",
]

[scrolling]
history = 10000
multiplier = 3

[window]
padding.x = 2
padding.y = 2

[cursor]
style = "Block"
unfocused_hollow = true

[font.normal]
family = "mononoki"
style = "Regular"
