[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"
bright_foreground = "#fbf1c7"
dim_foreground = "#a89984"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#1d2021"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

[colors.dim]
black = "#32302f"
red = "#9d0006"
green = "#79740e"
yellow = "#b57614"
blue = "#076678"
magenta = "#8f3f71"
cyan = "#427b58"
white = "#928374"

[[colors.indexed_colors]]
color = "#458588"
index = 66

[[colors.indexed_colors]]
color = "#689d6a"
index = 72

[[colors.indexed_colors]]
color = "#98971a"
index = 106

[[colors.indexed_colors]]
color = "#8ec07c"
index = 108

[[colors.indexed_colors]]
color = "#83a598"
index = 109

[[colors.indexed_colors]]
color = "#cc241d"
index = 124

[[colors.indexed_colors]]
color = "#b16286"
index = 132

[[colors.indexed_colors]]
color = "#b8bb26"
index = 142

[[colors.indexed_colors]]
color = "#d65d0e"
index = 166

[[colors.indexed_colors]]
color = "#fb4934"
index = 167

[[colors.indexed_colors]]
color = "#d79921"
index = 172

[[colors.indexed_colors]]
color = "#d3869b"
index = 175

[[colors.indexed_colors]]
color = "#fe8019"
index = 208

[[colors.indexed_colors]]
color = "#fabd2f"
index = 214

[[colors.indexed_colors]]
color = "#ebdbb2"
index = 223

[[colors.indexed_colors]]
color = "#fbf1c7"
index = 229

[[colors.indexed_colors]]
color = "#1d2021"
index = 234

[[colors.indexed_colors]]
color = "#282828"
index = 235

[[colors.indexed_colors]]
color = "#32302f"
index = 236

[[colors.indexed_colors]]
color = "#3c3836"
index = 237

[[colors.indexed_colors]]
color = "#504945"
index = 239

[[colors.indexed_colors]]
color = "#665c54"
index = 241

[[colors.indexed_colors]]
color = "#7c6f64"
index = 243

[[colors.indexed_colors]]
color = "#928374"
index = 245

[[colors.indexed_colors]]
color = "#a89984"
index = 246

[[colors.indexed_colors]]
color = "#bdae93"
index = 248

[[colors.indexed_colors]]
color = "#d5c4a1"
index = 250
